### ISSUE TITLE
The source directory does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by buscon** [v7b1/vb_UGens#1]
Hi, 

When I try to compile this library i get the following error:

 $ cmake -DSC_PATH="path/to/sc-src" -DCMAKE_BUILD_TYPE=RELEASE ..
CMake Error: The source directory "/home/marcello/.local/share/SuperCollider/Extensions/vb_UGens" does not appear to contain CMakeLists.txt.

the "path/to/sc-src" is actually the right path to my SC source directory, I left here as a reference.

It looks like a CMakeLists.txt file is missing in the root folder.

**Comment by v7b1** [comment]
Sorry, just saw this now... 
you need to step into the project folder and create the build folder (mkdir build), step into this newly created build folder and THEN execute 'cmake -DSC_PATH="path/to/sc-src" -DCMAKE_BUILD_TYPE=RELEASE ..'
Maybe the README wasn't up to date at the time of writing.
